version: '3.8'

services:
  db:
    image: mysql
    container_name: springboot3_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - rhein_data:/var/lib/mysql

volumes:
  rhein_data: