server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://${DEV_DB_HOST}:${DEV_DB_PORT}/${DEV_DB_NAME}?createDatabaseIfNotExist=true
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    name: ${DEV_DB_NAME}
  jpa:
    hibernate:
      ddl-auto: update


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG