server:
  error:
    include-stacktrace: always

spring:
  application:
    name: springboot3-essentials
  datasource:
    url: jdbc:mysql://localhost:3306/dealer?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE